import 'records/domain/entities/resource_spec.dart';

/// true  = sign in with the Elyvori API and show the live agents dashboard.
/// false = a standalone offline-first app that opens straight on its modules.
const bool useElyvoriAgents = false;

/// The modules of this app, generated by Elyvori from the client's request.
const List<ResourceSpec> appResources = <ResourceSpec>[
  ResourceSpec(
    key: 'patients',
    title: 'المرضى',
    icon: 'people',
    description: 'إدارة ملفات ومعلومات المرضى',
    fields: [
      FieldSpec(key: 'patient_name', label: 'اسم المريض', type: FieldType.text, required: true),
      FieldSpec(key: 'phone_number', label: 'رقم الهاتف', type: FieldType.phone, required: true),
      FieldSpec(key: 'birth_date', label: 'تاريخ الميلاد', type: FieldType.date, required: false),
      FieldSpec(key: 'medical_history', label: 'التاريخ المرضي', type: FieldType.longText, required: false),
    ],
  ),
  ResourceSpec(
    key: 'appointments',
    title: 'المواعيد',
    icon: 'calendar',
    description: 'جدولة ومتابعة مواعيد الكشف',
    fields: [
      FieldSpec(key: 'appointment_title', label: 'عنوان الموعد', type: FieldType.text, required: true),
      FieldSpec(key: 'patient_name', label: 'اسم المريض', type: FieldType.text, required: true),
      FieldSpec(key: 'appointment_date', label: 'تاريخ ووقت الموعد', type: FieldType.date, required: true),
      FieldSpec(key: 'status', label: 'مؤكد', type: FieldType.boolean, required: false),
    ],
  ),
  ResourceSpec(
    key: 'treatments',
    title: 'العلاجات',
    icon: 'medical',
    description: 'تسجيل الخطط العلاجية والوصفات الطبية',
    fields: [
      FieldSpec(key: 'treatment_name', label: 'اسم العلاج أو الدواء', type: FieldType.text, required: true),
      FieldSpec(key: 'patient_name', label: 'اسم المريض', type: FieldType.text, required: true),
      FieldSpec(key: 'dosage', label: 'الجرعة وطريقة الاستخدام', type: FieldType.text, required: false),
      FieldSpec(key: 'notes', label: 'ملاحظات طبية', type: FieldType.longText, required: false),
    ],
  ),
  ResourceSpec(
    key: 'invoices',
    title: 'الفواتير',
    icon: 'invoice',
    description: 'إدارة المدفوعات والفواتير الطبية',
    fields: [
      FieldSpec(key: 'invoice_number', label: 'رقم الفاتورة', type: FieldType.text, required: true),
      FieldSpec(key: 'patient_name', label: 'اسم المريض', type: FieldType.text, required: true),
      FieldSpec(key: 'amount', label: 'المبلغ', type: FieldType.number, required: true),
      FieldSpec(key: 'is_paid', label: 'تم الدفع', type: FieldType.boolean, required: false),
    ],
  ),
];
